version: '3.7'


services:
  db:
    image: mysql:8.0
    restart: always
    ports:
      - 3307:3306
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: ${DATABESE_NAME}
    container_name: compraVenta
    volumes:
      - ./mysql_data:/var/lib/mysql
volumes:
  mysql_data: