export { Inventario } from './inventario.entity';
export { Caja } from './caja.entity';
export { Venta } from './venta.entity';
export { Transaccion } from './transaccion.entity';
export { Traslado } from './traslado.entity';
export { Compra } from './compra.entity';
export { DetallesCompra } from './detalles-compra.entity';
export { Almacen } from './almacen.entity';
export { Cliente } from './cliente.entity';
